config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'users/home', to: 'users#home', as:'user_home'
  post '/deliveries', to: 'deliveries#create'
  patch '/deliveries/update_status', to: 'deliveries#update_status'
  patch '/driver_home/load_car', to: 'deliveries#load_car', as: :load_car
  patch '/driver_home/start_delivery', to: 'deliveries#start_delivery', as: :start_delivery
  patch '/deliveries/:id/done', to: 'deliveries#done', as: 'delivery_done'
  root "pages#login"
  get '/deliveries', to: 'deliveries#index'
  post 'charge', to: 'users#charge'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :name
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end



  protected


  def after_sign_up_path_for(resource)
    root_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  

  def create
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end


  def after_sign_in_path_for(resource)
    user_home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def home
        if current_user.role == "driver"
            render "driver_home"
        elsif current_user.role == "ww"
            render "ww_home"
        else
            @user_deliveries = Delivery.where(customer_id: current_user.id)
            @user_deliveries.each do |delivery|
                puts delivery.attributes
            end
            render "standard_home" 
        end
    end

    def charge
    end
end

app/views/users/driver_home.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTommQLmagc-sVra_yksEV9CEzzhDWEAc"></script>


<% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete ,class: "log-out-link-driver" %>
<% end %>

<%= form_tag load_car_path, method: :patch do %>
    <%= submit_tag "Load car", class:"load-car" %>
<% end %>

<%= form_tag start_delivery_path, method: :patch do %>
  <%= submit_tag "Start delivery", class: "start-delivery" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Tracking Number</th>
      <th>Customer</th>
      <th>Street</th>
      <th>House Number</th>
      <th>Dimensions</th>
      <th>Coordinates</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% Delivery.where(status: ['On the way to the destination', 'Loading car'], driver_id: current_user.id).each do |delivery| %>
      <tr>
        <td><%= delivery.tracking_number %></td>
        <td><%= delivery.customer.email %></td>
        <td><%= delivery.street %></td>
        <td><%= delivery.house_number %></td>
        <td><%= delivery.height %> x <%= delivery.width %> x <%= delivery.depth %></td>
        <td><%= delivery.latitude %> x <%= delivery.longitude %>
        <td><%= delivery.status %></td>
        <td class = "td-button">
          <% if delivery.status == 'On the way to the destination' %>
            <%= button_to '🗸', delivery_done_path(delivery), method: :patch, class: "done-button" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="map" style="height: 400px;"></div>

<script>
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= 53.209749 %>, lng: <%= 6.530806 %>},
    zoom: 8
  });


  var directionsService = new google.maps.DirectionsService();
  var directionsRenderer = new google.maps.DirectionsRenderer({map: map});


  var deliveryCoords = <%= raw Delivery.where(status: "On the way to the destination", driver_id: current_user.id).pluck(:latitude, :longitude).to_json %>;
  deliveryCoords = deliveryCoords.map(function(coord) {
    return new google.maps.LatLng(coord[0], coord[1]);
  });

  deliveryCoords.unshift(new google.maps.LatLng(<%= 53.209749 %>, <%= 6.530806 %>));

  var request = {
    origin: deliveryCoords[0],
    destination: deliveryCoords[deliveryCoords.length - 1],
    waypoints: deliveryCoords.slice(1, -1).map(function(coord) {
      return {
        location: coord,
        stopover: true
      };
    }),
    optimizeWaypoints: true,
    travelMode: 'DRIVING'
  };

  directionsService.route(request, function(result, status) {
    if (status == 'OK') {
      directionsRenderer.setDirections(result);
    }
  });
</script>

app/views/users/home.html.erb
<h1>Welcome to your home page</h1>

<p>Your email address is: <%= current_user.email %></p>

<button onclick="toggleForm()">Create delivery</button>

<div id="form-container" style="display:none">
  <%= form_tag("/deliveries", method: "post") do %>
      <%= hidden_field_tag :customer_id, current_user.id %>
      <%= label_tag "Street" %>
      <%= text_field_tag "delivery[street]" %>
      <br>
      <%= label_tag "House number" %>
      <%= text_field_tag "delivery[house_number]" %>
      <br>
      <%= label_tag "Height" %>
      <%= text_field_tag "delivery[height]" %>
      <br>
      <%= label_tag "Width" %>
      <%= text_field_tag "delivery[width]" %>
      <br>
      <%= label_tag "Depth" %>
      <%= text_field_tag "delivery[depth]" %>
      <br>
      <%= submit_tag "Submit" %>
  <% end %>
</div>

<h2>Orders</h2>
<% @user_deliveries.each do |order| %>
  <p>
    Street: <%= order.street %> <br>
    House number: <%= order.house_number %> <br>
    Dimensions: <%= order.height %> x <%= order.width %> x <%= order.depth %> <br>
    Status: <%= order.status %> <br>
    Tracking Number: <%= order.tracking_number %>
  </p>
<% end %>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% end %>

app/views/users/standard_home.html.erb
<h1>Disruptive Delivery</h1>
<h4>Delivery made simple</h4>

<!-- <p>Hello, <%= current_user.email %></p> -->

<button class ="create-delivery" onclick="toggleForm()">Create delivery</button>

<div id="form-container" style="display:none">
  <%= form_tag("/deliveries", method: "post") do %>
      <%= hidden_field_tag :customer_id, current_user.id %>
      <%= label_tag "Street" %>
      <%= text_field_tag "delivery[street]", nil, style: "width: 54%" %>
      <br>
      <%= label_tag "House number" %>
      <%= text_field_tag "delivery[house_number]", nil, style: "width: 47%" %>
      <br>
      <%= label_tag "Height" %>
      <%= text_field_tag "delivery[height]", nil, style: "width: 41%" %>
      <br>
      <%= label_tag "Width" %>
      <%= text_field_tag "delivery[width]", nil, style: "width: 34%" %>
      <br>
      <%= label_tag "Depth" %>
      <%= text_field_tag "delivery[depth]", nil, style: "width: 28%" %>
      <br>
      <%= submit_tag "Submit" %>
  <% end %>
  <%= form_tag charge_path, id: "payment-form" , class: "short-form" do %>
    <div class="form-row">
      <label for="card-element">
      </label>
      <div id="card-element"></div>
      <div id="card-errors" role="alert"></div>
    </div>
  <% end %>
</div>

<h2 class = "orders-header"></h2>
<div class="scrollable-dashboard">
  <table>
  <thead>
    <tr>
      <th>Street</th>
      <th>House number</th>
      <th>Dimensions</th>
      <th>Status</th>
      <th>Tracking Number</th>
    </tr>
  </thead>
  <tbody>
    <% @user_deliveries.each do |order| %>
      <tr>
        <td><%= order.street %></td>
        <td><%= order.house_number %></td>
        <td><%= order.height %> x <%= order.width %> x <%= order.depth %></td>
        <td><%= order.status %></td>
        <td><%= order.tracking_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<div class="road-container">
  <div class="road"></div>
  <div class="red-truck"></div>
  <div class="car"></div>
  <div class="white-line"></div>
</div>

<div class ="logo"></div>
<div class ="logo2"></div>


<script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe('pk_test_51MQSDuEM03nHu9w8mCc2cFV1HwsrtgsHDAnE0mQCJubYxjCoqUDNZVQ4qarwOuhii0p2PdkosflO2q7fNK5WoUM500MxAsTXhi');
  var elements = stripe.elements();
  var cardElement = elements.create('card');
  cardElement.mount('#card-element');
  cardElement.addEventListener('change', function (event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function (event) {
    event.preventDefault();
    stripe.createToken(cardElement).then(function (result) {
      if (result.error) {
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        stripeTokenHandler(result.token);
      }
    });
  });
  function stripeTokenHandler(token) {
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
    form.submit();
  }
</script>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "log-out-link" %>
<% end %>

app/views/users/ww_home.html.erb
<script>
  document.getElementById('update-form').addEventListener('submit', function(event) {
    event.preventDefault();
    const trackingNumber = document.getElementById('tracking-number').value;
    const xhr = new XMLHttpRequest();
    xhr.open('PATCH', '/deliveries/update_status');
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-CSRF-Token', document.getElementsByName('authenticity_token')[0].content);
    xhr.onload = function() {
      if (xhr.status === 200) {
        const delivery = JSON.parse(xhr.responseText).delivery;
        const deliveryRow = document.getElementById(`delivery-${delivery.id}`);
        deliveryRow.innerHTML = `
          <td>${delivery.tracking_number}</td>
          <td>${delivery.customer.email}</td>
          <td>${delivery.street}</td>
          <td>${delivery.house_number}</td>
          <td>${delivery.height} x ${delivery.width} x ${delivery.depth}</td>
          <td>${delivery.status}</td>
        `;
      }
    };
    xhr.send(`tracking_number=${trackingNumber}`);
  });
</script>

<%= form_tag '/deliveries/update_status', method: :patch, id: 'update-form' do %>
    <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
    <%= label_tag 'Tracking number' %>
    <%= text_field_tag 'tracking_number', '', id: 'tracking-number' %>
    <%= submit_tag 'Update status' %>
<% end %>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "log-out-link-ww" %>
<% end %>

<h1>Deliveries Inside Warehouse</h1>


<table>
  <thead>
    <tr>
      <th>Tracking Number</th>
      <th>Customer</th>
      <th>Street</th>
      <th>House Number</th>
      <th>Dimensions</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% Delivery.where(status: ['Inside Warehouse', 'Loading car']).each do |delivery| %>
      <tr id="delivery-<%= delivery.id %>">
        <td><%= delivery.tracking_number %></td>
        <td><%= delivery.customer.email %></td>
        <td><%= delivery.street %></td>
        <td><%= delivery.house_number %></td>
        <td><%= delivery.height %> x <%= delivery.width %> x <%= delivery.depth %></td>
        <td><%= delivery.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>